# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: jupyter@googlegroups.com
author_name: Jupyter Development Team
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: server
labextension_name: '@jupyterlab/chat'
mimetype: ''
mimetype_name: ''
project_short_description: A chat extension for Jupyterlab
python_name: jupyterlab_chat
repository: https://github.com/QuantStack/jupyterlab-chat
test: true
viewer_name: ''

